/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_richard_glestutorial_GLRenderer */

#ifndef _Included_com_richard_glestutorial_GLRenderer
#define _Included_com_richard_glestutorial_GLRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_richard_glestutorial_GLRenderer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_richard_glestutorial_GLRenderer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_richard_glestutorial_GLRenderer
 * Method:    nativeOnReSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_richard_glestutorial_GLRenderer_nativeOnReSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_richard_glestutorial_GLRenderer
 * Method:    nativeUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_richard_glestutorial_GLRenderer_nativeUpdate
  (JNIEnv *, jclass);

/*
 * Class:     com_richard_glestutorial_GLRenderer
 * Method:    nativeOnPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_richard_glestutorial_GLRenderer_nativeOnPause
  (JNIEnv *, jclass);

/*
 * Class:     com_richard_glestutorial_GLRenderer
 * Method:    nativeOnResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_richard_glestutorial_GLRenderer_nativeOnResume
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
